import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import { ClerkProvider, auth } from "@clerk/nextjs";

import "./globals.css";
import Provider from "./(providers)";
import AuthProvider from "./(providers)/AuthProvider";
import ReactQueryProvider from "./(providers)/ReactQueryProvider";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { userId } = auth();

    return (
        <ClerkProvider>
            <html lang="en">
                <body className={font.className}>
                    <ReactQueryProvider>
                        <Provider>
                            <AuthProvider />
                            {children}
                        </Provider>
                    </ReactQueryProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
